from pyuvm.s17_uvm_reg_enumerations import *
from pyuvm.s18_uvm_reg_block        import *
from pyuvm.s19_uvm_reg_field        import *
from pyuvm.s20_uvm_reg              import *
from pyuvm.s21_uvm_reg_map          import *
from pyuvm.s22_uvm_mem              import *
from pyuvm.s23_uvm_reg_item         import *
from pyuvm.s24_uvm_reg_includes     import *
from pyuvm.s25_uvm_adapter          import *
from pyuvm.s26_uvm_predictor        import *