from s17_pyuvm_reg_enumerations import *
from s18_pyuvm_reg_block        import *
from s19_pyvum_reg_field        import *
from s20_pyuvm_reg              import *
from s21_pyuvm_reg_map          import *
from s22_pyuvm_mem              import *
from s23_pyuvm_reg_item         import *
from s24_pyuvm_reg_includes     import *
from s25_pyuvm_adapter          import *
from s26_pyuvm_predictor        import *