// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package TinyALUreg_pkg;
    typedef struct {
        logic [7:0] next;
    } TinyALUreg__SRC__data0__in_t;

    typedef struct {
        logic [7:0] next;
    } TinyALUreg__SRC__data1__in_t;

    typedef struct {
        TinyALUreg__SRC__data0__in_t data0;
        TinyALUreg__SRC__data1__in_t data1;
    } TinyALUreg__SRC__in_t;

    typedef struct {
        logic [15:0] next;
    } TinyALUreg__RESULT__data__in_t;

    typedef struct {
        TinyALUreg__RESULT__data__in_t data;
    } TinyALUreg__RESULT__in_t;

    typedef struct {
        logic [4:0] next;
    } TinyALUreg__CMD__op__in_t;

    typedef struct {
        logic next;
    } TinyALUreg__CMD__start__in_t;

    typedef struct {
        logic next;
    } TinyALUreg__CMD__done__in_t;

    typedef struct {
        logic [6:0] next;
    } TinyALUreg__CMD__reserved__in_t;

    typedef struct {
        TinyALUreg__CMD__op__in_t op;
        TinyALUreg__CMD__start__in_t start;
        TinyALUreg__CMD__done__in_t done;
        TinyALUreg__CMD__reserved__in_t reserved;
    } TinyALUreg__CMD__in_t;

    typedef struct {
        TinyALUreg__SRC__in_t SRC;
        TinyALUreg__RESULT__in_t RESULT;
        TinyALUreg__CMD__in_t CMD;
    } TinyALUreg__in_t;

    typedef struct {
        logic [4:0] value;
    } TinyALUreg__CMD__op__out_t;

    typedef struct {
        logic value;
    } TinyALUreg__CMD__start__out_t;

    typedef struct {
        logic value;
    } TinyALUreg__CMD__done__out_t;

    typedef struct {
        logic [6:0] value;
    } TinyALUreg__CMD__reserved__out_t;

    typedef struct {
        TinyALUreg__CMD__op__out_t op;
        TinyALUreg__CMD__start__out_t start;
        TinyALUreg__CMD__done__out_t done;
        TinyALUreg__CMD__reserved__out_t reserved;
    } TinyALUreg__CMD__out_t;

    typedef struct {
        TinyALUreg__CMD__out_t CMD;
    } TinyALUreg__out_t;
endpackage