name: Regression Tests

on:
  push:
    branches:
    - master
    - ral_dev
  pull_request:
    branches:
    - master
    - ral_dev
  workflow_dispatch:

jobs:

  tests:
    name: Python ${{matrix.python-version}} | cocotb ${{matrix.cocotb-version}}
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          # Test all Python versions with latest cocotb
          - python-version: "3.9"
            cocotb-version: "2.0"
            vhdl-sim: "nvc"
          - python-version: "3.10"
            cocotb-version: "2.0"
            vhdl-sim: "nvc"
          - python-version: "3.11"
            cocotb-version: "2.0"
            vhdl-sim: "nvc"
          - python-version: "3.12"
            cocotb-version: "2.0"
            vhdl-sim: "nvc"
          - python-version: "3.13"
            cocotb-version: "2.0"
            vhdl-sim: "nvc"
          # Test other cocotb versions
          # Must use GHDL as VHDL simulator as NVC is only supported in cocotb 1.9+
          - python-version: "3.9"
            cocotb-version: "1.6"
            vhdl-sim: "ghdl"
          - python-version: "3.9"
            cocotb-version: "1.7"
            vhdl-sim: "ghdl"
          - python-version: "3.9"
            cocotb-version: "1.8"
            vhdl-sim: "ghdl"
          - python-version: "3.9"
            cocotb-version: "1.9"
            vhdl-sim: "nvc"

    steps:
    - uses: actions/checkout@v7
      with:
        # GitHub PR's create a merge commit, and Actions are run on that commit.
        # Codecov's uploader needs the previous commit (tip of PR branch) to associate coverage correctly.
        # A fetch depth of 2 provides enough information without fetching the entire history.
        fetch-depth: 2

    - uses: ./.github/actions/test-pyuvm
      with:
        python-version: ${{matrix.python-version}}
        cocotb-version: ${{matrix.cocotb-version}}
        vhdl-sim: ${{matrix.vhdl-sim}}
        pyuvm-package-source: "."
        coverage: "true"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
      with:
        disable_search: true
        plugins: noop
        files: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        fail_ci_if_error: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master') }}
